### PR TITLE
Changes cherry picked from develop pull request of the same story

### PR DESCRIPTION
**Pull request by satya-sanikommu**

### CODE REVIEW

**Comment by carlbm** [comment]
The changes look the same as the changes from the original PR

**Review by carlbm — APPROVED** [review]

**Comment by satya-sanikommu** [comment]
Testing completed. No functional changes and No functional regression issues. As this is a performance improvement for processing/publishing the DataLock events, the performance change can only be measured on Shadow environment with large numbers of events to process.

**Comment by satya-sanikommu** [comment]
Ready to merge

**Comment by satya-sanikommu** [comment]
This branch was initially planned to merge into Develop (https://github.com/SkillsFundingAgency/das-providerpayments/pull/146).  As DC team has accepted to take these changes into R07 Submissions release, this branch got merged into 'R07-Submissions-Release version'

**Pull request merged**
