### PR TITLE
Update prerun script to materialise a view prior to using it

### PR DESCRIPTION
**Pull request by carlbm**
One element of the view increased in size from 66k to 9m rows for R06 and the view was timing out.

### CODE REVIEW

**Comment by carlbm** [comment]
Apologies for the branch name....

**Review by lazcool — APPROVED** [review]
Reviewed by Paul & Phil.
Replicating what's in live. Pull request matches Jira Task.

**Comment by satya-sanikommu** [comment]
@carlbm  I have updated the base branch to 'R07-MonthEnd-Release', as this needs to go into the release branch first, then the release branch gets merged into Develop

**Comment by carlbm** [comment]
This has been superceded by DPP-1330 payments due rework

**Pull request closed without merging**
