### PR TITLE
Fixed issue with EAS tests failing when run after other tests

### PR DESCRIPTION
**Pull request by carlbm**

### CODE REVIEW

**Comment by chrisfoster76** [comment]
@satya-sanikommu @rohannpradhan2404 given that this change is to the acceptance tests only, and has no functional change, are you happy for it to be merged, or do you want a ticket on the DPP board and an opportunity to test it?

**Comment by satya-sanikommu** [comment]
@chrisfoster76 Ticket created for this already DPP-1125 and is in TechReview. Please don't merge this yet, once the review is completed, we run the tests and verify. Then we will merge

**Review by chrisfoster76 — APPROVED** [review]
Minor test change only

**Comment by satya-sanikommu** [comment]
Testing completed. No functional changes and no regression issues. Acceptance test failures reduced to 16. Ready to merge

**Pull request merged**
