### PR TITLE
Dpp 907 events api emitting duplicate removed data lock events

### PR DESCRIPTION
**Pull request by tom-gough**

### CODE REVIEW

**Comment by chrisfoster76** [comment]
One observation around the style of tests - the When* method name (Setup) does not appear in the Test Explorer view, so it's hard to see what's wrong at a glance.

Also, this ideally needs testing the context of a period end (see parameters in RunTask() call). It might be worth seeing if we can do something like [TestCase(context = Submission)] and [TestCase(xcontext = PeriodEnd)] but I think the separate setup steps for each might make that too untidy?

**Review by davehowlett — COMMENTED** [review]
looks ok other than Chris's comments. All the Unit/Int tests pass and the normal acceptance tests also pass.

**Comment by tom-gough** [comment]
Test naming I have fixed, as for the test cases I have taken a stab based on what you said about period end and submission and the test helper method names, looks like it should be right, please confirm.

**Review by carlbm — DISMISSED** [review]
Can you add a happy path for period end

**Review by chrisfoster76 — DISMISSED** [review]
Still getting a bit of unexpected behaviour here due I think to the test data helpers. Given the setup for these tests, I would expect to be able to assert not only no data lock event for the price episode identifier but actually no data lock event at all. But, I do get a data lock event.

The reason lies with the price episode identifiers set in the test data helpers I think. So, if I look at the db after running, I can see:

1. A previously emitted datalock event with identifier "Ep 1" (your identifier is 1-1-1-2017-04-01)

2. A datalock DLOCK_07 against the commitment with an identifier of 99-99-99-2017-04-01

3. A newly emitted datalock event with an identifier of 99-99-99-2017-04-01 - which you'd expect because this is not the same identifier as in 1.

So, I think we need to pass in/trace through where the identifiers are set at each stage and be able to control them. The knock on effect on other tests may be an issue.

Second point - I thought we'd said that you'd add the data lock via [DataLock].[DataLockEvents] so that the test covers the "copy reference data" script, not directly into the Reference schema?

**Review by tom-gough — COMMENTED** [review]
Can't approve as it's my own PR, but @chrisfoster76 's changes look fine.

**Comment by satya-sanikommu** [comment]
@tom-gough Testing completed. Ran minimum acceptance tests,No regression issues. Ready to merge

**Pull request merged**
